import {
  javascript,
  html,
  css,
  reactjs,
  nextJs,
  tailwind,
  nodejs,
  git,
  typeScript,
  figma,
  outlier,
  TheAmazingEgypt,
  Portfolio,
  next_Dashboard,
  GoldXchange,
} from "../assets";

export const navLinks = [
  {
    id: "about",
    title: "About",
  },
  {
    id: "work",
    title: "Work",
  },
  {
    id: "contact",
    title: "Contact",
  },
];

const technologies = [
  {
    name: "HTML 5",
    icon: html,
  },
  {
    name: "CSS 3",
    icon: css,
  },
  {
    name: "JavaScript",
    icon: javascript,
  },

  {
    name: "React JS",
    icon: reactjs,
  },
  {
    name: "Next-js",
    icon: nextJs,
  },
  {
    name: "Tailwind CSS",
    icon: tailwind,
  },
  {
    name: "Node JS",
    icon: nodejs,
  },

  {
    name: "git",
    icon: git,
  },
  {
    name: "TypeScript",
    icon: typeScript,
  },
  {
    name: "Figma",
    icon: figma,
  },
];

const experiences = [
  {
    title: "AI Trainer",
    company_name: "Outlier ",
    icon: outlier,
    iconBg: "#383E56",
    date: "November 2024 - Present [FreeLance]",
    points: [
      "Help train generative artificial intelligence models.",
      "Craft and answer questions related to computer science to assist in training AI models.",
      "Evaluate and rank code generated by AI models..",
    ],
  },
  //Next iconBg #E6DEDD
];

const projects = [
  {
    name: "TheAmazingEgypt",
    description:
      "TheAmazingEgypt is a project that showcases the breathtaking beauty of Egypt, highlighting its most stunning and iconic destinations. It offers an unforgettable experience for visitors looking to explore and immerse themselves in the wonders of Egypt.",
    tags: [
      {
        name: "react",
        color: "blue-text-gradient",
      },
      {
        name: "TypeScript",
        color: "green-text-gradient",
      },
      {
        name: "Tailwind",
        color: "pink-text-gradient",
      },
    ],
    image: TheAmazingEgypt,
    source_code_link: "https://github.com/SerajEldeen/TheAmazingEgypt",
    prereview_link: "https://the-amazing-egypt.netlify.app/",
  },
  {
    name: "GoldXchange",
    description:
      "GoldXchange is a simple web platform that allows users to exchange and track gold prices seamlessly. It features Google and GitHub authentication for secure login, a responsive design for accessibility, and a structured privacy policy to comply with Google Cloud requirements. The website is deployed on Netlify, ensuring smooth performance and availability.",
    tags: [
      {
        name: "Next-auth",
        color: "blue-text-gradient",
      },
      {
        name: "React-query",
        color: "pink-text-gradient",
      },
      {
        name: "Tailwind",
        color: "green-text-gradient",
      },
    ],
    image: GoldXchange,
    source_code_link: "https://github.com/SerajEldeen/GoldXchange",
    prereview_link: "https://goldxchange.netlify.app/",
  },
  {
    name: "Nextjs-Dashboard",
    description:
      "This project showcases a simple and dynamic dashboard designed to display real-time statistics updates. It includes visualization graphs to enhance data representation, providing better insights and improving decision-making processes.",
    tags: [
      {
        name: "Next-js",
        color: "blue-text-gradient",
      },
      {
        name: "TypeScript",
        color: "pink-text-gradient",
      },
      {
        name: "Tailwind",
        color: "green-text-gradient",
      },
    ],
    image: next_Dashboard,
    source_code_link: "https://github.com/SerajEldeen/Next-Dashboard",
    prereview_link:
      "https://next-dashboard-git-master-seraj-eldeen-abdullahs-projects.vercel.app/",
  },

  {
    name: "Portfolio",
    description:
      "This portfolio showcases the projects I’ve worked on and demonstrates my skills in building modern web applications. You’ll find detailed descriptions of each project, the technologies I used, and the results achieved. If you’d like to collaborate or have any questions, feel free to reach out to me via the contact section.",
    tags: [
      {
        name: "react",
        color: "blue-text-gradient",
      },
      {
        name: "Framer motion",
        color: "green-text-gradient",
      },
      {
        name: "Tailwind",
        color: "pink-text-gradient",
      },
    ],
    image: Portfolio,
    source_code_link: "https://github.com/SerajEldeen/Portfolio",
    prereview_link: "https://serajeldeen13.netlify.app/",
  },
];

export { technologies, experiences, projects };
