import {
  javascript,
  html,
  css,
  reactjs,
  nextJs,
  tailwind,
  nodejs,
  mongodb,
  git,
  typeScript,
  figma,
  outlier,
  TheAmazingEgypt,
  GoldXchange,
  BookStore,
  Hidaya,
  depi,
  postgresql,
  PostgreStore,
} from "../assets";

export const navLinks = [
  {
    id: "about",
    title: "About",
  },
  {
    id: "work",
    title: "Work",
  },
  {
    id: "contact",
    title: "Contact",
  },
];

const technologies = [
  {
    name: "HTML 5",
    icon: html,
  },
  {
    name: "CSS 3",
    icon: css,
  },
  {
    name: "JavaScript",
    icon: javascript,
  },

  {
    name: "React JS",
    icon: reactjs,
  },
  {
    name: "Next-js",
    icon: nextJs,
  },
  {
    name: "Tailwind CSS",
    icon: tailwind,
  },
  {
    name: "Node JS",
    icon: nodejs,
  },
  {
    name: "Mongo DB",
    icon: mongodb,
  },
  {
    name: "PostgreSQL",
    icon: postgresql,
  },
  {
    name: "git",
    icon: git,
  },
  {
    name: "TypeScript",
    icon: typeScript,
  },
  {
    name: "Figma",
    icon: figma,
  },
];

const experiences = [
  {
    title: "AI Trainer",
    company_name: "Outlier ",
    icon: outlier,
    iconBg: "#383E56",
    date: "November 2024 - March 2025",
    points: [
      "Help train generative artificial intelligence models.",
      "Craft and answer questions related to computer science to assist in training AI models.",
      "Evaluate and rank code generated by AI models.",
    ],
  },
  {
    title: "Software Engineer Intern",
    company_name: "DEPI ",
    icon: depi,
    iconBg: "#E6DEDD",
    date: "June 2025 - Present",
    points: [
      "Learn and apply software engineering principles in a professional environment.",
      "Work with a team to develop and maintain software applications.",
    ],
  },
];

const projects = [
  {
    name: "PostgreStore",
    description:
      "PostgreStore is a complete PERN stack project that implements CRUD operations for authenticated users.",
    tags: [
      {
        name: "PostgreSql",
        color: "blue-text-gradient",
      },
      {
        name: "Express.js",
        color: "green-text-gradient",
      },
      {
        name: "React.js",
        color: "pink-text-gradient",
      },
      {
        name: "DaisyUI",
        color: "blue-text-gradient",
      },
    ],
    image: PostgreStore,
    source_code_link: "https://github.com/SerajEldeen/PostgreStore",
    prereview_link: "https://github.com/SerajEldeen/PostgreStore",
  },
  {
    name: "Hidaya",
    description:
      "Hidaya is a modern, user-friendly website designed with a noble intention: to raise awareness about the teachings of Islam. The project showcases Islamic habits, values, and lifestyle through elegant UI, interactive components, and responsive design.",
    tags: [
      {
        name: "Next.js",
        color: "blue-text-gradient",
      },
      {
        name: "TypeScript",
        color: "green-text-gradient",
      },
      {
        name: "Tailwind",
        color: "pink-text-gradient",
      },
    ],
    image: Hidaya,
    source_code_link: "https://github.com/SerajEldeen/TheAmazingEgypt",
    prereview_link: "https://hidayaa.netlify.app/",
  },
  {
    name: "TheAmazingEgypt",
    description:
      "TheAmazingEgypt is a project that showcases the breathtaking beauty of Egypt, highlighting its most stunning and iconic destinations. It offers an unforgettable experience for visitors looking to explore and immerse themselves in the wonders of Egypt.",
    tags: [
      {
        name: "react",
        color: "blue-text-gradient",
      },
      {
        name: "TypeScript",
        color: "green-text-gradient",
      },
      {
        name: "Tailwind",
        color: "pink-text-gradient",
      },
    ],
    image: TheAmazingEgypt,
    source_code_link: "https://github.com/SerajEldeen/TheAmazingEgypt",
    prereview_link: "https://the-amazing-egypt.netlify.app/",
  },
  {
    name: "Book-Store",
    description:
      "Book-Store is a user-friendly web application that allows users to manage books through full CRUD operations, with all data stored in a MongoDB database.",
    tags: [
      {
        name: "React.js",
        color: "blue-text-gradient",
      },
      {
        name: "Node.js",
        color: "green-text-gradient",
      },
      {
        name: "Express.js",
        color: "pink-text-gradient",
      },
      {
        name: "MongoDB",
        color: "blue-text-gradient",
      },
    ],
    image: BookStore,
    source_code_link: "https://github.com/SerajEldeen/Book-Store",
    prereview_link: "https://book-store-frontend-eight-xi.vercel.app/",
  },
  {
    name: "GoldXchange",
    description:
      "GoldXchange is a responsive web app for tracking and exchanging gold prices, featuring Google/GitHub login and a clear privacy policy.",
    tags: [
      {
        name: "Next-auth",
        color: "blue-text-gradient",
      },
      {
        name: "React-query",
        color: "pink-text-gradient",
      },
      {
        name: "Tailwind",
        color: "green-text-gradient",
      },
    ],
    image: GoldXchange,
    source_code_link: "https://github.com/SerajEldeen/GoldXchange",
    prereview_link: "https://goldxchange.netlify.app/",
  },
];

export { technologies, experiences, projects };
