import {
  javascript,
  html,
  css,
  reactjs,
  redux,
  tailwind,
  nodejs,
  git,
  outlier,
  TheWildOasis,
  GeminiClone,
  Portfolio,
  typeScript,
} from "../assets";

export const navLinks = [
  {
    id: "about",
    title: "About",
  },
  {
    id: "work",
    title: "Work",
  },
  {
    id: "contact",
    title: "Contact",
  },
];

const technologies = [
  {
    name: "HTML 5",
    icon: html,
  },
  {
    name: "CSS 3",
    icon: css,
  },
  {
    name: "JavaScript",
    icon: javascript,
  },

  {
    name: "React JS",
    icon: reactjs,
  },
  {
    name: "Redux Toolkit",
    icon: redux,
  },
  {
    name: "Tailwind CSS",
    icon: tailwind,
  },
  {
    name: "Node JS",
    icon: nodejs,
  },

  {
    name: "git",
    icon: git,
  },
  {
    name: "TypeScript",
    icon: typeScript,
  },
];

const experiences = [
  {
    title: "AI Trainer",
    company_name: "Outlier ",
    icon: outlier,
    iconBg: "#383E56",
    date: "November 2024 - Present [FreeLance]",
    points: [
      "Help train generative artificial intelligence models.",
      "Craft and answer questions related to computer science to assist in training AI models.",
      "Evaluate and rank code generated by AI models..",
    ],
  },
  //Next iconBg #E6DEDD
];

const projects = [
  {
    name: "TheWildOasis",
    description:
      "Wild Oasis is a modern and responsive hotel booking application designed to streamline the process of managing reservations and room availability. The project focuses on delivering a seamless and user-friendly interface by leveraging the latest technologies.",
    tags: [
      {
        name: "react",
        color: "blue-text-gradient",
      },
      {
        name: "supabase",
        color: "green-text-gradient",
      },
      {
        name: "styled-components",
        color: "pink-text-gradient",
      },
    ],
    image: TheWildOasis,
    source_code_link: "https://github.com/SerajEldeen/TheWildOasis",
    prereview_link:
      "https://the-wild-oasis-53ay-git-master-seraj-eldeen-abdullahs-projects.vercel.app/",
  },
  {
    name: "Gemini Clone",
    description:
      "Gemini Clone is an AI-powered web application inspired by Google's Generative AI capabilities. It allows users to interact with a generative AI model, providing real-time responses based on user input. The project showcases the integration of AI APIs with a modern frontend, delivering a seamless and interactive user experience.",
    tags: [
      {
        name: "react",
        color: "blue-text-gradient",
      },
      {
        name: "useContext",
        color: "green-text-gradient",
      },
      {
        name: "css",
        color: "pink-text-gradient",
      },
    ],
    image: GeminiClone,
    source_code_link: "https://github.com/SerajEldeen/GeminiClone",
    prereview_link:
      "https://gemini-clone-git-master-seraj-eldeen-abdullahs-projects.vercel.app/",
  },
  {
    name: "Portfolio",
    description:
      "This portfolio showcases the projects I’ve worked on and demonstrates my skills in building modern web applications. You’ll find detailed descriptions of each project, the technologies I used, and the results achieved. If you’d like to collaborate or have any questions, feel free to reach out to me via the contact section.",
    tags: [
      {
        name: "react",
        color: "blue-text-gradient",
      },
      {
        name: "Framer motion",
        color: "green-text-gradient",
      },
      {
        name: "Tailwind",
        color: "pink-text-gradient",
      },
    ],
    image: Portfolio,
    source_code_link: "https://github.com/SerajEldeen/Portfolio",
    prereview_link:
      "https://portfolio-git-master-seraj-eldeen-abdullahs-projects.vercel.app/",
  },
];

export { technologies, experiences, projects };
